compiled/sfx/clftZandiRadio_Loop.ogg
compiled/sfx/tmnaCreditsMusic.ogg

Replacement SFX for Zandi's radio and end credits. Updated by Cyan.

New Radio and Credits SFX via Cyan

---

compiled/dat/GreatZero_District_GreatZeroInterior.prp

Ported from Gehn Shard subversion.

Fix GreatZero activation responder.

---

compiled/dat/GreatTreePub_District_GreatTree.prp
compiled/dat/GreatTreePub_District_Pub.prp
compiled/dat/GreatTreePub_District_Textures.prp
sources/GreatTreePub/GreatTreePub.blend

Great Tree Pub as it was before August 2020 MOULa update

Great Tree Pub 1 to 1 10-1-2020

---

compiled/dat/Neighborhood_District_nb01LiveAdditions.prp

- [VidCamScreensaver] Changed to kExplicitBounds

Fix flat convex hull in the Neighborhood that caused crashes.

---

compiled/dat/Serene_District_Snowfall.prp
compiled/sfx/Serene_flocksndloop.ogg

Re-adds Serene's snow and bugs. Fix by Ehren.

Add Serene Particle Effects

---

compiled/dat/Neighborhood_District_nb01.prp
sources/Neighborhood/nb01Marbles.json

~~WIP: This currently only fixes the four marbles in the entry area. Those marbles were already halfway set up for the sounds, the objects were just connected (very) incorrectly. The other three lack sounds entirely so need some more work.~~
This is a script generated fix for the Neighborhood firemarble kickable sound effects.

Fix Neighborhood fire marble SFX

---

compiled/dat/GUI_District_telescope.prp

Enlarged the black mask of the telescope for ultra-widescreen resolutions

---

compiled/dat/HeekEnglish.loc
compiled/dat/HeekFrench.loc
compiled/dat/HeekGerman.loc
compiled/dat/HeekItalian.loc
compiled/dat/HeekSpanish.loc

Original references Garrison, but the name is Gahreesen now
Translations were done with Google Translate.

Ayoheek message change to reference Gahreesen

---

compiled/dat/HeekGerman.loc

Additional translations provided by Minasunda for Heek

Additional translations provided

---

compiled/dat/Tiam.loc
compiled/dat/Tiam_District_BuiltIn.prp
compiled/dat/Tiam_District_Default.prp
compiled/dat/Tiam_District_Textures.prp

Adds the Age of Tiam by ametist. PR created on her behalf with her permission.

Add Tiam PRP and LOC files

---

compiled/dat/KIEnglish.loc
compiled/dat/KIFrench.loc
compiled/dat/KIGerman.loc
compiled/dat/KIItalian.loc
compiled/dat/KISpanish.loc

Also fix a couple capitalization goofs in English emotes and make Italian /buddies and /neighbors match the KI folder names properly. Should be merged with companion H-uru/Plasma PR.

Add emote aliases and add some simple foreign language commands

---

compiled/dat/DescentEnglish.loc
compiled/dat/PhilReltoEnglish.loc

Exactly what it says on the tin. :)

Remove triple-double-quote endings from Descent and Phil's Relto journals

---

compiled/dat/Dereno_District_DrnoBackpack.prp
compiled/dat/Ercana_District_Bakery.prp
compiled/dat/Ercana_District_PlantExterior01.prp
compiled/dat/Ercana_District_PlantExterior02.prp

Adds Backpack2 as a collectible in Dereno pod and correct Backpack model in Er'cana

---

compiled/dat/KIEnglish.loc
compiled/dat/KIFrench.loc
compiled/dat/KIGerman.loc
compiled/dat/KIItalian.loc
compiled/dat/KISpanish.loc

German translation approved, French and Italian are just best guesses for now.

Add /cough and its emote string (plus translations)

---

compiled/dat/GlobalAnimations_District_FemaleDanceRetro.prp
compiled/dat/GlobalAnimations_District_MaleDanceRetro.prp
compiled/dat/KIEnglish.loc
compiled/dat/KIFrench.loc
compiled/dat/KIGerman.loc
compiled/dat/KIItalian.loc
compiled/dat/KISpanish.loc
sources/avatar/animations/FemaleDanceRetro.max
sources/avatar/animations/MaleDanceRetro.max

Supersedes #41 to add the UU/CC-style dance as `/retrodance` command, with Haz's blessing to try to get this put to bed. Please ensure this is merged with the companion Plasma PR.

Add KI LOC strings, animation PRPs, and source max files for retro dance

---

compiled/dat/Serene_District_Textures.prp
compiled/dat/Serene_District_mainRoom.prp

* Adjust footprint decal
* Fix compartment door lighting
* Adjust some collision
* Fix a few UV mapping issues on the big rock

Serene 2022 Q1 Updates

---

compiled/dat/GlobalEnglish.loc
compiled/dat/GlobalFrench.loc
compiled/dat/GlobalGerman.loc
compiled/dat/NexusEnglish.loc
compiled/dat/NexusFrench.loc
compiled/dat/NexusGerman.loc
compiled/dat/NexusItalian.loc
compiled/dat/NexusSpanish.loc

* Add GoMePubNew messages
* Add AgeName Defs for GoMePubNew in Global LOCs.
Companion PR to https://github.com/H-uru/Plasma/pull/1130 .

Update Nexus LOCs

---

compiled/dat/Garrison_District_NexusBlackRoom.prp
compiled/dat/Garrison_District_NexusWhiteRoom.prp
compiled/dat/Garrison_District_Textures.prp
compiled/dat/Garrison_District_grsnWallRoomClimbingPhys.prp

During testing of physx changes on Trollland found that some parts of the wall game did not function correctly.
Also found a few bugs during testing and normal gameplay that need correcting as it allows you to win the game in ways not intended.
@EhrenCG also found that the shadows in the yellow panel area were missing and that ABM had a better version.

Wall Game fixes

---

compiled/sfx/TiamBtnShort.ogg
compiled/sfx/TiamFirstHalfElfs3.ogg
compiled/sfx/TiamKnappljud3.ogg
compiled/sfx/TiamSten3.ogg
compiled/sfx/TiamStenLoop3.ogg
compiled/sfx/TiamWatLapping3.ogg
compiled/sfx/Tiam_Liddown.ogg
compiled/sfx/Tiam_Pling.ogg
compiled/sfx/Tiam_Pling1.ogg
compiled/sfx/Tiam_Pling2.ogg
compiled/sfx/Tiam_button2.ogg
compiled/sfx/Tiam_dblbuttnew.ogg
compiled/sfx/Tiam_gitter.ogg
compiled/sfx/Tiam_razzle2.ogg
compiled/sfx/Tiam_wind.ogg
compiled/sfx/Tiamwaterstream3.ogg

Adds the missing Tiam sound effects to fix issue #125 .

Add Tiam SFX

---

compiled/dat/Neighborhood02_District_krelCommonRm.prp
compiled/sfx/krelFanQ22022_eng.ogg
compiled/sfx/krelFanQ22022_eng.sub
compiled/sfx/krelFanQ22022_fre.ogg
compiled/sfx/krelFanQ22022_fre.sub
compiled/sfx/krelFanQ22022_ger.ogg
compiled/sfx/krelFanQ22022_ger.sub

Post-processed audio and subtitles for Q2 fan update messages for Kirel podium.
English script by: DapperAndy
English voice: Tyion
French translation and voice: skyisblu
German translation and voice: Taliana (as Anna Windisch)
PRP diff attached. Please let me know if anything looks funny.
[krelCommon_diff.txt](https://github.com/H-uru/moul-assets/files/8963956/krelCommon_diff.txt)

Add new audio, subtitles, and modified PRP for Kirel 2022-Q2 update message

---

compiled/dat/Tiam_District_Default.prp
compiled/dat/Tiam_District_Textures.prp

Update Tiam to the latest version.

Tiam Q2 2022 Update

---

compiled/dat/VeeTsah.loc

Adds the following names and entries to the LOC for the journals:
* David "Different Dave" Mains
* Frank "Stungthumbz" Whiting
* Joan Daisy "Tink" Berkey
It also:
* Updates Battle Bots Boy's entry
* Arranges the elements alphabetically

VeeTsah LOC updates

---

compiled/dat/Neighborhood02_District_krelCommonRm.prp
compiled/sfx/krelFanQ42022_eng.ogg
compiled/sfx/krelFanQ42022_eng.sub
compiled/sfx/krelFanQ42022_fre.ogg
compiled/sfx/krelFanQ42022_fre.sub

Kirel fan audio for Q4 2022 release.
Directed/Written by DapperAndy
English audio by Tyion
French audio by skyisblue
German audio may be provided later
---------------
PRP changes (and instructions for me for future quarters):
1. Add Sound Buffers for new audio files
* External: true
* Format: PCM
* Channels: 1
* Bit Rate: 16
* Block Align: 2
* Sample Rate: 44100
* Avg Bytes/Sec: 88200
* Filename: krelFanQ{qtr}{year}_{lang}.ogg
2. Edit Sound Buffers using "Edit PRC" and set the Length value to {length of audio in milliseconds} * 88.2. Use nearest whole number.
Add new Win32StreamingSound named after new quarter.
* Set all the settings to make it match prior quarter's values except for soft volume(s) and data buffer.
3. Set Soft Volume for new Sound to the Soft Region Intersect named …

Add Q42022 fan audio in English and French

---

.github/lint_matchers.json
.github/workflows/lint.yml
eol.py

Add EOL linter action.

---

compiled/dat/ChisoPreniv.loc
compiled/dat/ChisoPreniv_District_Chiso.prp
compiled/dat/ChisoPreniv_District_FanContent.prp
compiled/dat/ChisoPreniv_District_LowerLevel.prp
compiled/dat/ChisoPreniv_District_Textures.prp

* Brings Chiso up to current MOULa version

Chiso Preniv Q3-4 2022 Updates

---

compiled/dat/Neighborhood02_District_krelCommonRm.prp
compiled/sfx/krelFanQ42022_ger.ogg
compiled/sfx/krelFanQ42022_ger.sub

I need to verify everything works nicely and double-check that the timings are correct, but feel free to start reviewing.
Translation and recording: Taliana
Script (English) by: DapperAndy
Audio processing and subtitle timings: Zaroth

Add 2022 Q4 fan audio and subtitles in German

---

.gitattributes
compiled/avi/NewPlayerIntro.webm
sources/avi/Relto23IntroEngFreGerFinal.mkv

Fan Video designed to replace the Yeesha Intro played when you first arrive in Relto age
Voice Overs done by
English - Maurus
French - Skyisblu
German - Taliana
Included the Higher Quality version in the source files
The webm version was done with quality settings of 31 in Handbrake

Fan Relto video to replace Yeesha intro

---

compiled/dat/GoMePubNew_District_Alcoves.prp
compiled/dat/GoMePubNew_District_Entry.prp
compiled/dat/GoMePubNew_District_GoMeConfRoom.prp
compiled/dat/GoMePubNew_District_GoMePub.prp
compiled/dat/GoMePubNew_District_Holidays.prp
compiled/dat/GoMePubNew_District_Mysterium.prp
compiled/dat/GoMePubNew_District_StoreRoom.prp
compiled/dat/GoMePubNew_District_Textures.prp
compiled/dat/GoMePubNew_District_gmpnCones.prp

* Adds new 2023 Mysterium Shirt and associated clickables (requires Hazado's GlobalClothing update)
* Adds TCT shirt clickable and wiring

GoMePubNew Update 2.03.2023

---

compiled/dat/Tiam.loc
compiled/dat/Tiam_District_Default.prp
compiled/dat/Tiam_District_Textures.prp

2.04.2023:
* fixed a critical error on the ballpuzzle code
* adjusted and added clickable colliders for the green jewels and the ball
* added covers to the Journals
* adjusted some texture baking
* removed LOC whitespace (Doobes)

Tiam Update Q1 2023

---

compiled/sfx/ChisoPreniv_SecretDoorClose.ogg
compiled/sfx/ChisoPreniv_SecretDoorOpen.ogg

* Hotfix to add new hidden door sfx by Maurus

Chiso Preniv Hotfix 5.14.2023

---

compiled/dat/HeekEnglish.loc
compiled/dat/HeekFrench.loc
compiled/dat/HeekGerman.loc
compiled/dat/HeekItalian.loc
compiled/dat/HeekSpanish.loc

Script changes needed - https://github.com/H-uru/Plasma/pull/1446
Translation done with google translate.

Adds heek table quit message

---

compiled/dat/ACAEnglish.loc
compiled/dat/ACAFrench.loc
compiled/dat/ACAGerman.loc
compiled/dat/ACAItalian.loc
compiled/dat/ACASpanish.loc
compiled/dat/GlobalClothing_District_FemaleBracelets.prp
compiled/dat/GlobalClothing_District_MaleBracelets.prp
sources/avatar/clothing_bracelets/Icon_UHand_Bracelet.png
sources/avatar/clothing_bracelets/Icon_UHand_Bracelet.xcf
sources/avatar/clothing_bracelets/UHand_Bracelet_tint1.png
sources/avatar/clothing_bracelets/UHand_Bracelet_tint1.xcf
sources/avatar/clothing_bracelets/bracelet_export_mesh.blend
sources/avatar/clothing_bracelets/bracelet_export_mesh_f.blend

Add the "Bracelet" Clothing Item by default in the wardrobe:
[Changes.txt](https://github.com/user-attachments/files/17607866/Changes.txt)

Bracelet Clothing

---

compiled/dat/city_District_LibraryInterior.prp
compiled/dat/city_District_MuseumInteriorPage.prp
compiled/dat/city_District_library.prp
compiled/dat/city_District_libraryDoors.prp
compiled/dat/city_District_museumDoor.prp

Script files - https://github.com/H-uru/Plasma/pull/1462
Adds back the doors to the city age
Library - https://www.youtube.com/watch?v=eQN9g3_GvGw
Museum - https://youtu.be/cKd7t_hcM-A
Added actual collisions to the doors
Moved the exclusion region on/off to the beginning of the responder
These changes make it so your not running into invisible barriers when the door is opening. When the door is closing you will notice invisible barrier a little bit, but without that I was able to be pushed through the wall and fall through the ground to the basement. I feel that these changes make the doors a better experience than what happens in CC.

Adds back the doors to the City

---

compiled/dat/Neighborhood_District_nb01.prp

Scripts and SDL - https://github.com/H-uru/Plasma/pull/1458
Only change was to add this string to the python File mod "PythonFileImager02"
``<plPythonParameter ID="14" Type="String" Value="nb01PelletUploadState" />``

Add additional string option to Pellet Imager
