compiled/avi/CyanWorlds.webm, compiled/avi/Intro1.bik, compiled/avi/URULiveIntro.bik, compiled/avi/URULiveIntro.webm
These are the hastily converted videos we used on the Gehn Shard.
=> Replace unsupported Bink videos with WebM.

compiled/dat/Teledahn_District_tldnWorkroom.prp
Corrected the plSoundMsg in the workroom power stop responder to send the `kStop` command instead of `kPlay`, causing the screw turn noise to stop playing when the power is off. See original report on the [forum](https://forum.guildofwriters.org/viewtopic.php?p=75033#p75033).
=> [Teledahn] Fix spurious workroom noise.

compiled/dat/Personal_District_psnlMYSTII.prp
After discussion in the DirectX discord, it was revealed that old hardware TnL spot lights would revert to affecting everything if the difference between the inner and outer cones was zero. As of Windows 10 v2004, the light cones supposedly function as expected. Previously, the cones differed by approximately 0.05 radians, which must have been sufficient to trigger the nearly 20 year standing bug. This changeset sets the inner cone to zero degrees, allowing the spot light to affect the entirety of the Relto hut. The outer cone value is unchanged.
If you look at the values in the PRPs, remember that Plasma spot light cones are stored as half radians. The dark light's cone is now approximately 91.5 degrees.
=> Fix Relto dark hut problem in Windows 10 v2004+

compiled/dat/Neighborhood_District_nb01.prp
[nbClockGlobe_(Entire Animation)_anim_0] Added a third keyframe to the clock rotation animation to cause the clock to actually rotate. Also converted to uncompressed quat keyframes due to lossy compression breaking the animation.
=> Fix Neighborhood clock globe animation.

compiled/dat/city_District_ferry.prp
Wrong shirt was assigned in python file mod for first week shirt. This fixes that issue.
[Python File Mod - cPythFirstWeekShirtTakable - 4] Changed to "FReward_Launch"
[Python File Mod - cPythFirstWeekShirtTakable - 5] Changed to "MReward_Launch"
=> Fixes First Week Reward Clothing

compiled/dat/Teledahn_District_tldnHarvest.prp
[PXPhysical] Bendy Bridge
Changed the member group from kGroupDynamic to kGroupStatic. The previous setting is for kickables (which this bridge is not). PhysX does not allow for non-kinematic dynamic bodies to have triangle mesh bounds. Because of the improper member group, we were forcing PhysX to treat the triangle mesh bounds as a convex hull, making the whole bridge solid.
Or, as Simulation.0.log says:
`WARNING: 'BendyBridge' is a dynamic triangle mesh; this is not supported in PhysX 4... forcing to convex hull, sorry.`
=> Fix solid bendy bridge in Teledahn.

compiled/dat/Kadish_District_kdshGlowInTheDark.prp
Video of changes - https://youtu.be/Z2M48N6SyTQ
Scripts needed here - https://github.com/H-uru/Plasma/pull/951
Changed the Kadish Moon Elevator to be a Riding Animated Physical.
Changed timings so that you can jump into the elevator after it has left (up to 4 seconds after it has left)
Changed it so that the bottom elevator entrance blocker no longer interacts with the player at all
Its now possible to jump into the elevator as its leaving or leave it before it reaches the bottom
Fixed a spot in the video above were I clip through the geometry as the elevator is going down.
I lowered the collision mesh so this wont happen again.
=> Kadish moon elevator subworld no longer interacts with player

compiled/dat/GUI_District_bkBahroRockBook.prp, sources/textures/tga/GUI/xBahroPageRock_Original.tga, sources/textures/tga/GUI/xBahroPageRock_v3d.tga
CalumTraveler gave the Yeesha Symbol on the bahro stone the correct aspect and colorized it to match the original.
Original
New Version
=> Updated Bahro Book image with corrected Yeesha symbol

compiled/dat/Kadish_District_kdshGlowInTheDark.prp
Should fix the collision issues noticed by testers on Minkata shards.
Testers were able to glitch through collisions on the front part of the elevator when it was rising up
[Scene Object - Elevator Wall] Coordinate Interface removed.
[Coordinate Interface - SubWorld_New] Scene Object "Elevator Wall" removed from Children
[Generic Physical - Elevator Wall] Bottom face removed. Angled and moved to bottom section of elevator shaft.
=> Kadish Elevator fix

compiled/dat/Ercana_District_Canyon.prp, compiled/dat/Ercana_District_PelletRm.prp
Requires H-uru/Plasma#954
Per @dgelessus
> * Have the harvester docked at the facility, with the little cart moved up/inside the facility
> * Board the harvester without moving the cart back down (easiest by Reltoing out and returning via the original link-in point)
> * Set the harvester to backwards direction
> * Push the call button for the little cart (on the harvester control panel)
> * Before the little cart arrives at the harvester, start the harvester so it moves away from the facility without the cart
> Now once the little cart arrives at the bottom, both the cart and the harvester lower their wooden bridges. Normally the cart should now be connected to the harvester, but it isn't, because you moved the harvester away first. Now you can simply walk off the wooden bridges on the …
=> Er'cana Fix Rollup

compiled/dat/GlobalClothing_District_FemaleFan02.prp, compiled/dat/GlobalClothing_District_MaleFan02.prp
As of H-uru/Plasma#942, this is now supported. The GZ Pride shirt's icon is now very nice.
=> Re-export Fan02 clothing with PNG icons.

compiled/dat/Ercana_District_Canyon.prp, compiled/dat/Ercana_District_PlantExterior01.prp, compiled/dat/Ercana_District_Tunnel.prp
This is a collection of graphical fixes to Er'cana age.
All prps were resaved to fix any graphic issues due to textures locs possibly changing.
Canyon
Harvester cable next to ladder attached to nothing
Floating rocks and bushes under car ramp
Harvester call button floats
Spout on harvester clips through wings when harvester is moving away and cart is inside facility
See through area on harvester console
Journey cloth beside the harvester was floating
Z-flighting rocks near sinkhole and end of the line
Large Plants floating
Tunnel
Lights at top of car ramp have no view face modifier
All the lights in left tunnel are in wrong spot
2 top lights in right tunnel are gone
See out into world in between cart tunnels walkways
PlantExterior01
Water Tunnel doors need collisions when open
=> Fixes for Ercana Canyon

compiled/dat/GlobalMarkers_District_Markers.prp
This is accomplished by changing the RenderLevel on the DSpans from `0x40000000` (BlendRendMajorLevel) to `0x80000001` (LateRendMajorLevel + 1).
Partly addresses GitHub issue #18.
=> Fix render issues with user-created GZ Markers

compiled/dat/CityEnglish.loc, compiled/dat/CityFrench.loc, compiled/dat/CityGerman.loc, compiled/dat/GUI_District_BkBookImages.prp
The Negilahn journal cover inside city museum shows Ki journal when you click on it.
This fixes that issue.
Conflicts with PR #65
=> Negilahn Journal cover missing

compiled/dat/Ercana_District_Canyon.prp
The warning light on the harvester console was not lit correctly.
Old 
New 
The harvester Railing had a few stretched and z-fighting textures and a few sections that the normals were flipped. The end caps for the railing near the ladder were also missing.
Old
New
=> Additional Graphical Fixes for Ercana

compiled/dat/CustomAvatars_District_Quab.prp
This ensures that the Armature Effects object for the Quab footsteps has the correct RandomSoundMod set up for the "Stone" surface, not just the "Dirt" surface.
=> Fix Quab footsteps

compiled/dat/KIEnglish.loc, compiled/dat/KIFrench.loc, compiled/dat/KIGerman.loc, compiled/dat/KIItalian.loc, compiled/dat/KISpanish.loc
Flipped the LOC files through plLocalizationEditor with these results. Fixes bad alphabetization I did when adding ChatAge command by hand to the LOCs and adds empty NewClothing message element to all the non-English KI LOC files.
=> Re-alphabetize and add missing empty elements for KI LOCs

compiled/dat/city_District_canyon.prp, compiled/dat/city_District_courtyard.prp, compiled/dat/city_District_ferry.prp, compiled/dat/city_District_palace.prp
Resolves H-uru/moul-assets#107
Nexus Book and Ki Slot regions had a number of issues.
Fixed so you can always click the left side and it will add the link to you nexus.
Clicking on book will open the book.
=> Fix nexus KI slot regions in City

compiled/sfx/clftZandiOpen01a_eng.sub
Adding single subtitle file (easy to test with new character) as a sample to test the new feature. I was promised bonus points by Adam:
> I think there would be bonus points for breaking up the .sub PR into a single "demonstration" subtitle PR to go along with the core functionality and a larger one with the bulk load of the .subs. That way we can merge the functionality itself rather quickly and take time glancing over the subtitles themselves.
=> Add single subtitle file for Zandi's Cleft intro as a testing sample

compiled/dat/Personal_District_psnlMYSTII.prp
There was a collider for one of the pine trees between the bench and bahro pole.
When you turned on the autumn page it would hide the pine tree, but not the collider box around that tree.
=> Missing python file mod for pine tree collider

compiled/dat/city_District_harbor.prp
GZ beam animation end point is past its start point.
This give the impression that the GZ beam is skipping backwards when it gets to the arch.
Adjusted the end point so it better meets the start point.
=> Fix GZ Beam in city

compiled/dat/GlobalEnglish.loc, compiled/dat/GlobalFrench.loc, compiled/dat/GlobalGerman.loc, compiled/dat/GlobalItalian.loc, compiled/dat/GlobalSpanish.loc, compiled/dat/KIEnglish.loc, compiled/dat/KIFrench.loc, compiled/dat/KIGerman.loc, compiled/dat/KIItalian.loc, compiled/dat/KISpanish.loc
~~No translations available yet for command, default arg value, status messages, or error/usage message. I need to reach out to some translators in the OU discord to get at least French and German, probably. I'm not 100% happy with the wording in the error/usage message in English, though, so I'd like to get some suggestions from y'all and smooth that out first.~~
Reworked error/usage message to a place where I am reasonably happy with it. French and German translations kindly provided by skyisblu and @dgelessus, respectively. Some Spanish color names based on old college Spanish knowledge and Google but I don't expect we'll get a native translator for the rest of the functionality in Spanish ~~or in Italian~~ any time soon. I was wrong about the Italian functionality; Italian has been …
=> Add /textcolor command and supporting text elements

compiled/dat/GlobalEnglish.loc, compiled/dat/GlobalFrench.loc, compiled/dat/GlobalGerman.loc, compiled/dat/GlobalItalian.loc, compiled/dat/GlobalSpanish.loc, compiled/dat/KIEnglish.loc, compiled/dat/KIFrench.loc, compiled/dat/KIGerman.loc, compiled/dat/KIItalian.loc, compiled/dat/KISpanish.loc
Fix the misspelled LOC key string, fix German format based on feedback by dgelessus and Prad in the OU discord, and add baseline Italian and Spanish so they don't use the English format (which was definitely wrong).
=> Add and fix possessive formatters for foreign languages

compiled/dat/GlobalMarkers_District_Markers.prp
This fixes a crash, presumably introduced by #32, caused by references to a stale DSpan object. The crash could be observed by creating a marker game an attempting to add a marker to it.
=> Fix reference to stale DSpan object in Markers.

compiled/dat/KISpanish.loc
- Remove spaces in several emote command strings. Spaces in emotes are not acceptable. E.g., `/no sé` just does the `/no` "Shake Head" emote and a separate message afterwards just saying "<PlayerName>: sé". These were bad and confusing times.
- Remove duplicated emote commands `/nosé` and `/gracias`. Second instance of `/gracias` was replaced by `/agradecer` instead.
- Fixed the emote string for the `/agradecer` emote... because its message was in Italian. These were also bad and confusing times.
- Remove the `¡No te vayas por favor!` (roughly, "Please don't go!") part of the quit/logout confirmation message. Apparently a holdover from Choru, or so I am told. Anyway, none of the other languages get so emotional about a player quitting so it feels inappropriate to keep.
=> Remove spaces in Spanish emote commands and guilt-trip in quit confirmation

compiled/dat/Cleft_District_trailerCamPage.prp
This is the cleft camera flyby done in this trailer for Myst Online
https://www.youtube.com/watch?v=rLvkMJDrMAU
Clip of how I set up to trigger the camera and the flybys
https://www.youtube.com/watch?v=8An_EP3jVfk
This PRP will never load in any game due to the age file having the page set to be controlled by page loading.
Inside the age file Line 35
`Page=trailerCamPage,18,1`
needs to be changed to load the file
`Page=trailerCamPage,18`
=> Adds the cyan camera work done to create the trailer for Myst Online

compiled/dat/Personal_District_psnlMYSTII.prp
Got a request to fix the animation for the doors in Relto so they were properly centered in the grooves of the hut
Video of the new animation
https://youtu.be/Nj4YEjmUvI4
=> Fixes Relto door animations to be centered in doorframe

compiled/dat/KIEnglish.loc, compiled/dat/KIFrench.loc, compiled/dat/KIGerman.loc, compiled/dat/KIItalian.loc, compiled/dat/KISpanish.loc
Added as a fallback for the receiver client to use in case the sender did not send their pronoun LOC key somehow.
=> Add neutral possessive pronoun to use for receiver default in localized emotes

compiled/dat/GlobalEnglish.loc
Closes #59.
This updates the English Uru Credits journal by removing stale information about Bink, Boost, "Burn You Up, Burn You Down!", and AEGIA PhysX. Also updates all open source license credits to current from the [README](https://github.com/H-uru/Plasma#readme). ~~To review the changes, observe only the last commit.~~
Some other points that this PR dances around but should probably be answered:
- In many cases, these open source attributions are insufficient because upstream calls for the entire license text to be included. I don't think that's a good idea in this journal, but we do need to have a place (maybe just a text file installed with the client) with all the licenses pasted in. Vcpkg can actually help us with that.
- ~~Round-tripping the loc files through …
=> Update UruCredits journal.

compiled/dat/KIEnglish.loc, compiled/dat/KIFrench.loc, compiled/dat/KIGerman.loc, compiled/dat/KIItalian.loc, compiled/dat/KISpanish.loc
Primarily for use in chat logs for easier post-processing, e.g., to remove private messages or subtitles before posting chat logs to a forum post or blog or whatnot.
Will also turn on automatically for now when the user has used `/textcolor` to override default header color to indicate the chat context (I, for one, can never remember what the colors mean, though).
Sibling Plasma PR Coming Soon(TM).
=> KI chat context prefixes

.gitignore
Make sure to ignore the silly .vs folder because sometimes I'm a weirdo and edit LOCs in Visual Studio. Sometimes I like the VS compare better than a command-line `git diff`. 🤷
=> Add .vs folder to .gitignore file

.gitignore, compiled/dat/BaronCityOfficeEnglish.loc, compiled/dat/BaronCityOffice_District_BaronCityOffice.prp
Added the vault-only text content to the LOC directly. Fixed a couple typos and weird middle-of-line spacing. I can revert the latter commit if the typos are... desired.
PRP diff attached below. The exciting part is at the very end.
[BaronCityOffice_diff.txt](https://github.com/H-uru/moul-assets/files/8819951/BaronCityOffice_diff.txt)
=> Remove dependency of Sharper's journal on non-localized dynamic text in the vault

compiled/dat/GUI_District_GUIDialog04b.prp
Moves all the Visitor elements off screen and shrinks the space freed up from doing that
=> Remove Visitor selection from Character selection screen

compiled/dat/Neighborhood02_District_krelCommonRm.prp, compiled/dat/Neighborhood_District_CommonRoom.prp
Sets the Python file mod for the podium to proposed xPodium.py script (see https://github.com/H-uru/Plasma/pull/1238 ).
This is mostly for a test given @Hazado will likely have further updates for next quarter's Kirel audio.
=> Adjust Hoods' Podium Python Mods

compiled/dat/GlobalEnglish.loc, compiled/dat/GlobalFrench.loc
This PR brings the French credits journal contents (previously copied from Uru:CC credits, I believe) into alignment with the MOUL Uru credits that we have in English. I welcome any feedback on any French that needs to be adjusted. I made my best guesses based on existing CC credit contents for wording on titles/roles along with a sprinkling of Google Translate. There are still a few snippets in the Licences Open Source section that are in English if anyone wants to take a crack at writing those in French. I felt highly underqualified to try those myself. ;)
This PR also fix very minor spacing abnormalities in the English credits.
Videos of the results in-game.
English:
https://user-images.githubusercontent.com/94947971/195764911-b54d0f71-199d-4b72-b0c7-311805fd855c.mp4
French: …
=> French Uru credits in alignment with English contents

.gitattributes
Not sure how useful this is, but I noticed the new *.sub file type didn't have a line in the .gitattributes. As far as I'm concerned, it should be treated the same as other text files, like *.loc files.
=> Add *.sub line to .gitattributes

compiled/dat/Personal_District_psnlMYSTII.prp
Still not sure why the shading is wonky on this particular book since it matches how all the other books are set up, but it's particularly bad. The easy fix is the adjust the ambient (emissive) colour of the layers slightly to make it appear brighter.
Result in-game:
=> Fix shading on the hydrant Cleft book in Relto

compiled/dat/philRelto_District_PhilsRelto.prp
Fixes the Phil Relto rain so it starts immediately instead of after 30 seconds.
Diff:
[PhilRelto.txt](https://github.com/H-uru/moul-assets/files/10249537/PhilRelto.txt)
=> Phil Relto rain starts immediately

compiled/dat/Garden_District_trailerCamPage.prp, compiled/dat/Garrison_District_trailerCamPage.prp, compiled/dat/Neighborhood_District_trailerCamPage.prp, compiled/dat/Personal_District_trailerCamPage.prp, compiled/dat/Teledahn_District_trailerCamPage.prp, compiled/dat/city_District_trailerCamPage.prp
Files needed - https://github.com/H-uru/Plasma/pull/1270
These are camera shots that Cyan used in various trailers.
They are only triggerable by console commands.
Several ages include fake npc with no collisions, by default they are not visible and need a console command to turn on.
Console command - `Logic.TriggerResponder NameGoesHere`
**Garden** - https://www.youtube.com/watch?v=c_KI2TIO0CQ
- cam1
- camCharOn
- camCharOff
**Garrison** - https://www.youtube.com/watch?v=OFeGoOchIDs
- cam1
**Neighborhood** - https://www.youtube.com/watch?v=oj6DUZTf18w
- cam1
- cam2
- camCharOn
- camCharOff
**Personal** - https://www.youtube.com/watch?v=bF0PCqH8EiQ
- cam1
**Teledahn** - https://www.youtube.com/watch?v=LgPF3lknU2A
- cam1
- camCharOn
- camCharOff
**city** - …
=> Additional Cyan Trailer Cameras

compiled/dat/Ahnonay_District_EngineerHut.prp, compiled/dat/Ahnonay_District_Hub.prp, compiled/dat/Ahnonay_District_Vortex.prp
Fixed the Ahnonay Vogondola Entry and Exit animations so that they line up better than before.
This changes the entry exit seats animation and splits it into two animations, Up and Down.
I also adjusted the coordinate that the players entry and exit animation starts at.
Male:
Hut - https://www.youtube.com/watch?v=t1PcRT6uhOE
Hub - https://www.youtube.com/watch?v=_3EbQ4OtLdY
Female:
Hut - https://www.youtube.com/watch?v=QZeGAq5y7EM
Hub - https://www.youtube.com/watch?v=dthzhnggUgk
Diffs:
[EngineerHut.txt](https://github.com/H-uru/moul-assets/files/10248514/EngineerHut.txt)
[Hub.txt](https://github.com/H-uru/moul-assets/files/10248515/Hub.txt)
[Vortex.txt](https://github.com/H-uru/moul-assets/files/10248513/Vortex.txt)
=> Adjust Entry/Exit animations for Ahnonay Vogondola

compiled/dat/Serene.loc
Changed from Devokan story to the curated Serene-related journal written by Andy Legate, so the contents will match what is on MOULa since the Q4 2021 release. Edits for grammar and typos by Dot, Adam, and myself.
I'd be happy to rebase if needed after #190 has been merged, which will allow the diff to work properly as it will be comparing UTF-8 to UTF-8 before and after.
=> Update Serene.loc for new journal contents

compiled/dat/Garrison_District_NexusBlackRoom.prp, compiled/dat/Garrison_District_NexusWhiteRoom.prp, compiled/dat/Garrison_District_WallAdditions.prp, compiled/dat/Garrison_District_grsnObsRoom01Imager.prp, compiled/dat/Garrison_District_grsnObsRoom02Imager.prp, compiled/dat/Garrison_District_grsnWallRoomClimbingPhys.prp, compiled/dat/Garrison_District_trainingCenterObservationRooms.prp
Removed panel red lights fade out and back in when they are used, makes the blocker counters look a little better.
Made blocker screens not flicker anymore and half as transparant.
Flashing lights when book deploys now flash half as slow but the entire time the book is out
Made Building 2 map screen in conference rooms not flicker anymore and half as transparant.
Added visregions to all wall viewer screens in observation rooms to help with age lag
Reduced static opacity for observer rooms and nexi
Fixed the Green Button animations for both panels
Fixed bug with when the green buttons were supposed to be able to be clicked
=> Garrison Updates to Match Moula Q2

compiled/sfx/psnlVeeTsahMusic.ogg
With Mystler's blessing, retroactively applies the new cannen filtering effect to Relto's Veelay track. Going forward, these will be standardized and all new cannen tracks should use this same filter.
I apologize I was unable to properly upload this with Git LFS - I ran into issues getting this to work and had to resort to GitHub frontend instead. I will need someone to make the needed correction for me.
=> Add Cannen Filter to Veelay Music

compiled/dat/Ahnonay_District_Vortex.prp
The Ahnonay waterfall at the end will loop to the beginning of its loop every 31 seconds.
This causes a sudden texture reset every 31 seconds.
I adjusted the timings on the layer animations to do a perfect loop. (Hopefully)
The timings are very large now, so unless someone watches it from nearly an hour to see the end, it wont be noticed.
[AhnonayVortexDiff.txt](https://github.com/H-uru/moul-assets/files/10380223/AhnonayVortexDiff.txt)
=> Adjust Ahnonay waterfall loop to prevent sudden texture reset

compiled/dat/philRelto_District_PhilsRelto.prp, compiled/dat/philRelto_District_Textures.prp
Expands on @EhrenCG's work from Pull Request https://github.com/H-uru/moul-assets/pull/198 -
The underlying issue here was that the texture mapping used the original CC Relto mapping, despite the texture sheet provided for Phil's Relto being the exact same as MOUL's Relto, where most of the book textures have now been changed out for different ages. This resulted in several completely random books being shown in the POTS section on the shelf in Phil's Relto.
The solution in PR198 was to swap out the entire psnlbookcovers*40#0.hsm texture sheet with the CC one, which works, as it reverts the four POTS books to their textures from CC. However, we can take this change a step further by generating our own custom texture sheet designed specifically for Phil's Relto. Doing so allows us to make …
=> Adds Additional Updates to Phil's Relto Book Textures

compiled/dat/Neighborhood02_District_Textures.prp, compiled/dat/Neighborhood_District_Textures.prp
Revises the City Wall texture used in nb01/nb02 to remove details that would cause streaks in the overhead skybox. This new texture was sourced from the high-definition version of this same graphic contained in Intangibles files to prevent unnecessary loss from compression.
This is an **interim fix**, and is intended to be replaced by the more involved mesh, uv and texture fixes developed by @Hazado, @Emor-Dni-Lap et al. as part of #52 **Lake Lighting Project** once they are ready - Hazado has indicated this interim fix is OK in the meantime.
Before:
After:
=> Interim Fix for Hood/Kirel Skybox Streaking

compiled/dat/CityEnglish.loc, compiled/dat/CityFrench.loc, compiled/dat/CityGerman.loc, compiled/dat/CityItalian.loc, compiled/dat/CitySpanish.loc
Reported by Theo in OpenUru discord. Nick's Takotah rooftop note had gotten shoved down the page such that the signature no longer showed. The in-world model of the note shows the signature, as does the version of the note in CC according to Harley. The odd spacing was present for all translations. If this change is accepted, I'll make a change suggestion for the affected Russian LOC in #237 as well.
Before:
After:
=> Remove newlines causing weird spacing and missing signature on Nick's note

compiled/dat/GlobalClothing_District_Female.prp, sources/avatar/clothing/bas.avatar.female.max
Fix the Female avatar's Hands Options colors switch when selecting a different Hands Option:
The fix constist to put the Nails color in the layer 1 and to put the Gloves color in the layer 2,
for both the Fingerless Gloves and the Canvas Gloves.
It have been done in the "sources\avatar\clothing\bas.avatar.female.max" file with "3DS Max 2022", and then the "compiled\dat\GlobalClothing_District_Female.prp" file have been exported from the MAX file.
=> FemaleHandsOptionsColorsFix

compiled/dat/Cleft_District_Textures.prp, sources/textures/tga/Cleft/clftBeerCan.png, sources/textures/tga/Cleft/clftBeerCan.tga, sources/textures/tga/Cleft/clftChipsBag.png, sources/textures/tga/Cleft/clftChipsBag.tga
Equivalent to [Commit 0a34a4](https://foundry.openuru.org/gitblit/commit/?r=MOULa-current-content.git&h=0a34a4d81595ec5d08e70504269a55b2a3a1cec2) of [content/144 ("Cleft Revamp Bundle 1")](https://foundry.openuru.org/gitblit/tickets/?r=MOULa-current-content.git&h=144) in the OpenUru Foundry, included in the Q3 2024 update to MOULa. (For submission to H'uru I am splitting this bundle into three separate PRs for increased modularity.)
First batch of a planned series of improvements to help modernize The Cleft:
- Gives "ClftBeerCan" a facelift that reads more clearly as a water bottle and makes sure the "Sponakee" joke is actually legible.
- Slightly bumps up the res on ClftCD so this reads more clearly.
- In keeping with MOUL's intended "current day" setting, gives ClftChipsBag a …
=> Cleft Texture Improvements (Zandi Props & Skybox)

compiled/dat/Personal_District_Textures.prp, sources/textures/tga/Personal/psnlnewsky3verydark_40#2.png
Improves the variant of the stormy cloud texture Relto uses when the while the "green sky" (Veelay) page is active.
This is the counterpart to [content/145](https://foundry.openuru.org/gitblit/tickets/?r=MOULa-current-content.git&h=145) in the OpenUru Foundry, included in the Q3 2024 update to MOULa. However, there are some notable differences to be aware of, due to OU/MOULa and H'uru/moul-assets being slightly out of sync:
1. OU contains an optimization made by @Hazado which splits out all the fan content into separate PRPs so they are more modular, but this change is not present in H'uru/moul-asets yet. As such, the equivalent change here is applied directly to **Personal_District_Textures** rather than **Personal_District_psnlFanYeeshaPages01**, as the asset in question has not been …
=> Improve Green Storm Texture

CONTRIBUTING.md, README.md
This repository exists in an odd state where it kinda matches MOULa but not really. So, I've written up a draft contributor guide that lays out where I think this repo should fall in the ecosystem. Specifically, we are not trying to be the MOULa repository - that's not been our goal, ever really. Our goal, generally speaking, has been to provide a high quality baseline for any shard to operate off of.
One of our main sources of difficulty is that a lot of things that have been tested on Minkata and deployed to MOULa. Unfortunately, Minkata is a testing environment, not a review environment. This has led to content going to Cyan's shard that, even in cases going back almost a decade, isn't particularly up to snuff with the rest of the game. This has been accelerating over the last couple …
=> Add contributing guide.

compiled/dat/GlobalFrench.loc, compiled/dat/GlobalGerman.loc, compiled/dat/GlobalItalian.loc, compiled/dat/GlobalSpanish.loc
Very minor change: adjusts the translations for the "Big Blues" attributions using translations confirmed by fluent speakers who have been co-authored. Once approved, I will copy over this change & the other adjustments we made as part of #264 to OU for consistency.
=> Adjust Translations for "Big Blues" Attributions

compiled/dat/GUI_District_NavigationSettingsDialog.prp, sources/KI/xKIGUI.max
Supersedes #280 by fixing the issue in the Max file.
=> Fix two more options menu text boxes not using loc files.
